#!/bin/sh

set -u
set -e
trap onexit INT
trap onexit TERM
trap onexit EXIT

TMPDIR=

onexit()
{
	if [ ! "$TMPDIR" = "" ]; then
		rm -rf $TMPDIR
	fi
}

if [ -f turbovnc-2.1.91.x86_64.rpm ]; then
	rm -f turbovnc-2.1.91.x86_64.rpm
fi

umask 022
TMPDIR=`mktemp -d /tmp/turbovnc-build.XXXXXX`

mkdir -p $TMPDIR/RPMS
ln -fs `pwd` $TMPDIR/BUILD
rpmbuild -bb --define "_blddir $TMPDIR/buildroot" --define "_topdir $TMPDIR" \
	--target x86_64 pkgscripts/rpm.spec; \
cp $TMPDIR/RPMS/x86_64/turbovnc-2.1.91-20191120.x86_64.rpm \
	turbovnc-2.1.91.x86_64.rpm
